### PR TITLE
The new updated package submitted by Ericsson in Oct. 20th

### PR DESCRIPTION
**Pull request by ericzh31ericsson**
This is the new submission done by Ericsson, which includes several major features and some bug fix. For detail please check the document "Test Harness Software Feature Tracker v1.01.xlsx"

### CODE REVIEW

**Comment by cwilliams-ericsson** [comment]
Will need jsonschema python library, in addition to previous packages, to run this update.

**Comment by cwilliams-ericsson** [comment]
Issue found for some test cases where spectrumInquiry response does not include availableChannel object.  Requires some of the spectrumInquiry required json files to be updated.  Will be updated in this branch.

**Comment by dgcell20** [comment]
Should the registrationOptional.json file include the airInterface object and its radioTechnology parameter? That is, should something like the following be added?

"airInterface": { "$ref": "#/airInterface" }, 

 
   "airInterface": { 
     "type": "object", 
     "description": "Container for information on the air interface technology of the CBSD.", 
     "properties": { 
		"radioTechnology": { "enum": [ "E_UTRA","CAMBIUM_NETWORKS" ], 
                     "description": "Specifies the radio access technology the CBSD uses for operation in the CBRS band." }, 
      	} 
      },

**Comment by cwilliams-ericsson** [comment]
Hi Doug,

radioTechnology and airInterface were moved out of the optional json files to a separate file:

Configuration/ObjectListConfig\laterDefinedOptional.json

This was to allow later updates of these parameters (especially the airInterface list) without touching the base files in the jsonExpectedFolder.

**Comment by dgcell20** [comment]
Thanks Chris. I forgot some  parameters were being moved to separate file.
In looking at the laterDefinedOptional.json file.
Should:
"groupType": { "enum": [ "INTERFERENCE_COORDINATION" ], 

"radioTechnology": { "enum": [ "E_UTRA", "CAMBIUM_NETWORKS" ]

**Comment by cwilliams-ericsson** [comment]
Updated branch based on dgcell20's comments:

"groupType": { "enum": [ "INTERFERENCE_COORDINATION" ],
"radioTechnology": { "enum": [ "E_UTRA", "CAMBIUM_NETWORKS" ]

**Comment by cwilliams-ericsson** [comment]
Updated branch to fix issue with spectrumInquiry not containing availableChannel object(s).  Updated a few  expected json files, and a couple of constants.

**Comment by pawan25062** [comment]
Issue no.  47, 48 and 49 are raised for this branch.

**Comment by pawan25062** [comment]
Hi,

Fix for required and optional params in nested request json message (…  …
…Issue 46) -->  fix is working fine.

Regards,
Pawan

**Pull request merged**
