### PR TITLE
Bug fixes 2018 february

### PR DESCRIPTION
**Pull request by cwilliams-ericsson**
Some final fixes to test harness, including:
- updating json files to have common format for questions
- a few minor bug fixes

### CODE REVIEW

**Comment by dgcell20** [comment]
Here are a some additional minor updates that I believe could be addressed.
1.	Should WINNF_PROTOCOL_VERSION be changed to “v1.2”?
2.	Should the “site-packages_Mock_SAS_V_2_0.zip be deleted?
3.	Should the “allure-cli_for_Mock_SAS_V_2_0.zip” be deleted?
4.	jsonExpectedFolder/rel_In_Case_Of_Deregistration.json and spectrumInquiryAppearAlways.json, I think these two can be deleted as I did not see reference to them in a CSV test case file, but I would like someone else to confirm prior to deleting.

**Comment by cwilliams-ericsson** [comment]
5. Based on feedback we have received, do we want to disable heartbeatInterval checking entirely?  Or leave as is (fail on heartbeatInterval + 5 seconds currently)?

**Comment by cwilliams-ericsson** [comment]
Per internal discussion:

'1. Yes, will update to v1.2
'2. & 3, Those files will be deleted.
'4. , I checked:
rel_In_Case_Of_Deregistration.json is called directly from the code, not via a .csv file. --> Needs to remain
spectrumInquiryAppearAlways.json is not used in the code, or in .csv files --> can be deleted

**Comment by dgcell20** [comment]
Latest version of test harness tutorial refers to certificate filenames that do not currently exist in the certificate folder.
•	sasharnessprivkey.key
•	sasharnesscert.pem
•	cbsdpkichain.pem
•	dppkichain.pem
•	UUTCBSDprivkey.key
•	UUTCBSD.pem
•	TestLabSASPKIchain.pem
•	UUTDomainProxyprivkey.key
•	UUTDomainProxy.pem
•	TestLabSASPKIchain.pem
The tutorial also mentions the directory contains certificates for the "Unsuccessful TLS connection" tests.

**Comment by awaizkhan** [comment]
Following sanity check was performed on Ruckus eNB.


WINNF.FT.C.REG.3 | Single-Step registration for Category A CBSD | Pass
-- | -- | --
WINNF.FT.C.REG.8 | Missing Required parameters (responseCode 102) | Pass
WINNF.FT.C.REG.10 | Pending registration (responseCode 200) | Pass
WINNF.FT.C.REG.12 | Invalid parameter (responseCode 103) | Pass
WINNF.FT.C.REG.14 | Blacklisted CBSD (responseCode 101) | Pass
WINNF.FT.C.REG.16 | Unsupported SAS protocol version (responseCode 100) | Pass
WINNF.FT.C.GRA.1 | Unsuccessful Grant responseCode=400 (INTERFERENCE) | Pass
WINNF.FT.C.GRA.2 | Unsuccessful Grant responseCode=401 (GRANT_CONFLICT) | Pass
WINNF.FT.C.HBT.1 | Heartbeat Success Case (first Heartbeat Response) | Pass
WINNF.FT.C.HBT.3 | Heartbeat responseCode=105 (DEREGISTER) | Pass
WINNF.FT.C.HBT.4 | Heartbeat responseCode=500 (TERMINATED_GRANT) | Pass
WINNF.FT.C.HBT.5 | Heartbeat responseCode=501 (SUSPENDED_GRANT) in First Heartbeat Response | Pass
WINNF.FT.C.HBT.6 | Heartbeat responseCode=501 (SUSPENDED_GRANT) in Subsequent Heartbeat Response | Pass
WINNF.FT.C.HBT.7 | Heartbeat responseCode=502 (UNSYNC_OP_PARAM) | Pass
WINNF.FT.C.HBT.9 | Heartbeat Response Absent (First Heartbeat) | Pass
WINNF.FT.C.HBT.10 | Heartbeat Response Absent (Subsequent Heartbeat) | Pass
WINNF.FT.C.HBT.11 | Successful Grant Renewal in Heartbeat Test Case | Pass
WINNF.FT.C.DRG.1 | Successful Deregistration

**Pull request merged**
